### ISSUE TITLE
Error Message when fetching stock data

### ISSUE THREAD

**Issue by iSchorsch** [conradreisch/EODDataPortfolio-MoneyMoney#5] opened 2023-05-31 04:42 UTC
Hi, I really LOVE your extension! It works flawless for many month.

Now, when fetching stock data it throws the follwing message in MoneyMoney:

_Das SSL-Zertifikat des Servers Ihrer Bank wurde von macOS 13.4 als ungültig abgewiesen. Bitte versuchen Sie es später noch einmal oder wenden Sie sich für weitere Informationen an den Support Ihrer Bank.

Server-Adresse: https://eoddata.com/stockquote/NASDAQ/AAPL.htm_

Please look into the issue. Thank you so much!

**Comment by dark-m0de** [comment] 2023-05-31 08:44
Hi @iSchorsch,
thanks a lot for your feedback! The SSL error originates at EODDate and therefor is out of my control.  
However, it seems that EODData fixed the issue this morning (see screenshot below).
Can you confirm that the issue is fixed?
Best regards

<img width="579" alt="image" src="https://github.com/dark-m0de/EODDataPortfolio-MoneyMoney/assets/40696850/b4577867-7fc1-47b5-bb96-0a52721fea5f">

**Comment by iSchorsch** [comment] 2023-06-01 05:10
Thank you for your effort! The issue is fixed and can be closed. Thanks again for your great work!

**Comment by dark-m0de** [comment] 2023-06-01 05:53
Thank you. Closing the issue

**Closed as completed by dark-m0de** 2023-06-01 05:53 UTC
